package saber.kuns.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import saber.kuns.annotation.MybatisDao;
import saber.kuns.common.CrudDao;
import saber.kuns.entity.SysProperty;
import saber.kuns.entity.SysPropertyExample;

@MybatisDao
public interface SysPropertyMapper extends CrudDao<SysProperty> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    long countByExample(SysPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int deleteByExample(SysPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int insert(SysProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int insertSelective(SysProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    List<SysProperty> selectByExample(SysPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    SysProperty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysProperty record, @Param("example") SysPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysProperty record, @Param("example") SysPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysProperty record);

	/**
	 * genCode by category
	 * 
	 * @param params
	 * @return
	 */
	String genCode(Map<String, Object> params);
}