package saber.kuns.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import saber.kuns.annotation.MybatisDao;
import saber.kuns.entity.TblConsumption;
import saber.kuns.entity.TblConsumptionExample;

@MybatisDao
public interface TblConsumptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    long countByExample(TblConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int deleteByExample(TblConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int insert(TblConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int insertSelective(TblConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    List<TblConsumption> selectByExample(TblConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    TblConsumption selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TblConsumption record, @Param("example") TblConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TblConsumption record, @Param("example") TblConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_consumption
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblConsumption record);
}