package saber.kuns.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import saber.kuns.annotation.MybatisDao;
import saber.kuns.entity.TrafficCost;
import saber.kuns.entity.TrafficCostExample;

@MybatisDao
public interface TrafficCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    long countByExample(TrafficCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int deleteByExample(TrafficCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int insert(TrafficCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int insertSelective(TrafficCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    List<TrafficCost> selectByExample(TrafficCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    TrafficCost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TrafficCost record, @Param("example") TrafficCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TrafficCost record, @Param("example") TrafficCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TrafficCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traffic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TrafficCost record);
}