package saber.kuns.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TblAccomodation {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column tbl_accomodation.id
	 *
	 * @mbg.generated
	 */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.breakfast_cost
     *
     * @mbg.generated
     */
    private BigDecimal breakfastCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.lunch_cost
     *
     * @mbg.generated
     */
    private BigDecimal lunchCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.dinner_cost
     *
     * @mbg.generated
     */
    private BigDecimal dinnerCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_accomodation.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.id
     *
     * @return the value of tbl_accomodation.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.id
     *
     * @param id the value for tbl_accomodation.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.date
     *
     * @return the value of tbl_accomodation.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.date
     *
     * @param date the value for tbl_accomodation.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.breakfast_cost
     *
     * @return the value of tbl_accomodation.breakfast_cost
     *
     * @mbg.generated
     */
    public BigDecimal getBreakfastCost() {
        return breakfastCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.breakfast_cost
     *
     * @param breakfastCost the value for tbl_accomodation.breakfast_cost
     *
     * @mbg.generated
     */
    public void setBreakfastCost(BigDecimal breakfastCost) {
        this.breakfastCost = breakfastCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.lunch_cost
     *
     * @return the value of tbl_accomodation.lunch_cost
     *
     * @mbg.generated
     */
    public BigDecimal getLunchCost() {
        return lunchCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.lunch_cost
     *
     * @param lunchCost the value for tbl_accomodation.lunch_cost
     *
     * @mbg.generated
     */
    public void setLunchCost(BigDecimal lunchCost) {
        this.lunchCost = lunchCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.dinner_cost
     *
     * @return the value of tbl_accomodation.dinner_cost
     *
     * @mbg.generated
     */
    public BigDecimal getDinnerCost() {
        return dinnerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.dinner_cost
     *
     * @param dinnerCost the value for tbl_accomodation.dinner_cost
     *
     * @mbg.generated
     */
    public void setDinnerCost(BigDecimal dinnerCost) {
        this.dinnerCost = dinnerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.create_user
     *
     * @return the value of tbl_accomodation.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.create_user
     *
     * @param createUser the value for tbl_accomodation.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.create_time
     *
     * @return the value of tbl_accomodation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.create_time
     *
     * @param createTime the value for tbl_accomodation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.update_user
     *
     * @return the value of tbl_accomodation.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.update_user
     *
     * @param updateUser the value for tbl_accomodation.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.update_time
     *
     * @return the value of tbl_accomodation.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.update_time
     *
     * @param updateTime the value for tbl_accomodation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_accomodation.del_flag
     *
     * @return the value of tbl_accomodation.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_accomodation.del_flag
     *
     * @param delFlag the value for tbl_accomodation.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}