package saber.kuns.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TblConsumption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.consumption_val
     *
     * @mbg.generated
     */
    private BigDecimal consumptionVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.consumption_name
     *
     * @mbg.generated
     */
    private String consumptionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_consumption.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.id
     *
     * @return the value of tbl_consumption.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.id
     *
     * @param id the value for tbl_consumption.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.date
     *
     * @return the value of tbl_consumption.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.date
     *
     * @param date the value for tbl_consumption.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.consumption_val
     *
     * @return the value of tbl_consumption.consumption_val
     *
     * @mbg.generated
     */
    public BigDecimal getConsumptionVal() {
        return consumptionVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.consumption_val
     *
     * @param consumptionVal the value for tbl_consumption.consumption_val
     *
     * @mbg.generated
     */
    public void setConsumptionVal(BigDecimal consumptionVal) {
        this.consumptionVal = consumptionVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.consumption_name
     *
     * @return the value of tbl_consumption.consumption_name
     *
     * @mbg.generated
     */
    public String getConsumptionName() {
        return consumptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.consumption_name
     *
     * @param consumptionName the value for tbl_consumption.consumption_name
     *
     * @mbg.generated
     */
    public void setConsumptionName(String consumptionName) {
        this.consumptionName = consumptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.remark
     *
     * @return the value of tbl_consumption.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.remark
     *
     * @param remark the value for tbl_consumption.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.create_user
     *
     * @return the value of tbl_consumption.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.create_user
     *
     * @param createUser the value for tbl_consumption.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.create_time
     *
     * @return the value of tbl_consumption.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.create_time
     *
     * @param createTime the value for tbl_consumption.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.update_user
     *
     * @return the value of tbl_consumption.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.update_user
     *
     * @param updateUser the value for tbl_consumption.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.update_time
     *
     * @return the value of tbl_consumption.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.update_time
     *
     * @param updateTime the value for tbl_consumption.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_consumption.del_flag
     *
     * @return the value of tbl_consumption.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_consumption.del_flag
     *
     * @param delFlag the value for tbl_consumption.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}